/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.JsonApiBodyRequest;
import io.swagger.model.JsonApiBodyResponseErrors;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-09-10T20:41:16.454Z")

@Api(value = "listar", description = "the listar API")
public interface ListarApi {

    @ApiOperation(value = "Listado de personas por estado", nickname = "listarEstadoEstadoGet", notes = "Listado de personas por estado en la tabla personas de la base de datos.", response = JsonApiBodyRequest.class, tags={ "personas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = JsonApiBodyRequest.class),
        @ApiResponse(code = 404, message = "Personas no encontradas", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/listar/estado/{estado}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<JsonApiBodyRequest> listarEstadoEstadoGet(@ApiParam(value = "Estado de la persona",required=true) @PathVariable("estado") String estado);


    @ApiOperation(value = "Listado de personas", nickname = "listarGet", notes = "Listado de personas en la tabla personas de la base de datos.", response = JsonApiBodyRequest.class, tags={ "personas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = JsonApiBodyRequest.class),
        @ApiResponse(code = 404, message = "Persona(s) no encontrada(s)", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/listar",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<JsonApiBodyRequest> listarGet();


    @ApiOperation(value = "Busqueda de personas por id", nickname = "listarIdGet", notes = "Busqueda de personas por id en la tabla personas de la base de datos.", response = JsonApiBodyRequest.class, tags={ "personas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = JsonApiBodyRequest.class),
        @ApiResponse(code = 404, message = "Personas no encontradas", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/listar/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<JsonApiBodyRequest> listarIdGet(@ApiParam(value = "ID de la persona",required=true) @PathVariable("id") String id);


    @ApiOperation(value = "Listado de personas por roles", nickname = "listarRolRolGet", notes = "Listado de personas por roles en la tabla personas de la base de datos.", response = JsonApiBodyRequest.class, tags={ "personas", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "OK", response = JsonApiBodyRequest.class),
        @ApiResponse(code = 404, message = "Personas no encontradas", response = JsonApiBodyResponseErrors.class) })
    @RequestMapping(value = "/listar/rol/{rol}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<JsonApiBodyRequest> listarRolRolGet(@ApiParam(value = "Estado de la persona",required=true) @PathVariable("rol") String rol);

}
